### ISSUE TITLE
Ignition Intake Air temp correction 

### ISSUE THREAD

**Issue by OrchardPerformance** [FOME-Tech/FOME-Baseline#67]
Feature TS Notes:
Feature Status:
Known Problems:
Priority:
Suggested Fix:
Related Tickets:

Note - Why is this a 16x16 table? I doubt we need such granularity of control especially now we have multi dimensional mapping. 

![image](https://user-images.githubusercontent.com/49926376/209897725-65610983-6d08-4600-adfd-d0c1aba7a1e7.png)

**Comment by mi-hol** [comment]
> Did the axis fix get carried over?

do you mean "merged from a RE commit" with fix?

**Comment by OrchardPerformance** [comment]
Exactly that and it would seem yes.
